so much done, but it works pretty well now

diff --git a/nix/deploy b/nix/deploy
--- a/nix/deploy
+++ b/nix/deploy
@@ -1,30 +1,29 @@
 #!/usr/bin/env bash
+. functions/ssh
+. functions/hosts
 
-declare -A hosts=(
-  ["master1"]="10.22.20.11"
-  ["master2"]="10.22.20.12"
-  ["master3"]="10.22.20.13"
-  ["worker1"]="10.22.20.21"
-  ["worker2"]="10.22.20.22"
-  ["worker3"]="10.22.20.23"
-)
-
-if [ -z ${1} ]; then
+if [ -z "${1}" ]; then
   echo "You're doing it wrong"
-  exit
+  exit 1
 fi
 
+if ! HOST_IP=$(get_ip "${1}"); then
+  echo "Error getting ip: ${HOST_IP}"
+  exit 1
+fi
+
+ping_ssh "${HOST_IP}"
+
 if [ "${2}" = "copy" ]; then
-  scp root@"${hosts[${1}]}":/etc/rancher/rke2/rke2.yaml "${1}".yaml
-  sed -i "s/127.0.0.1/${hosts[${1}]}/g" "${1}".yaml
+  scp root@"${HOST_IP}":/etc/rancher/rke2/rke2.yaml "${1}".yaml
+  sed -i "s/127.0.0.1/${HOST_IP}/g" "${1}".yaml
   exit 0
 fi
 
 if [ "${2}" = "copy-token" ]; then
   mkdir -p extra_files
-  scp root@"${hosts[${1}]}":/var/lib/rancher/rke2/server/node-token extra_files/join.token
+  scp root@"${HOST_IP}":/var/lib/rancher/rke2/server/node-token extra_files/join.token
   exit 0
 fi
 
-nix run github:nix-community/nixos-anywhere -- --flake .#"${1}" --extra-files ./extra_files wonko@"${hosts[${1}]}"
-
+nix run github:nix-community/nixos-anywhere -- --flake .#"${1}" --extra-files ./extra_files wonko@"${HOST_IP}"
diff --git a/nix/doit b/nix/doit
--- a/nix/doit
+++ b/nix/doit
@@ -1,14 +1,28 @@
 #!/usr/bin/env bash
+. functions/kube
+. functions/hosts
 
+if ! HOST_IP=$(get_ip "master1"); then
+  echo "Error getting ip: ${HOST_IP}"
+  exit 1
+fi
+
+echo "Deploying to master1"
 ./deploy master1
-echo -n "Press enter when node is up"
-read -r
-
+echo "Copying kubeconfig from master1"
 ./deploy master1 copy
+echo "Copying join token from master1"
 ./deploy master1 copy-token
+
+echo "Waiting for kubeapi port to open"
+wait_for_connection "${HOST_IP}" 6443
+
+echo "Waiting for kubernetes to be ready on master1"
+wait_for_ready master1 master1.yaml
 
 ADDITIONAL_NODES=('master2' 'master3' 'worker1' 'worker2' 'worker3')
 
 for node in "${ADDITIONAL_NODES[@]}"; do
-  echo ./deploy "${node}"
+  echo "Deploying to ${node}"
+  ./deploy "${node}"
 done
